.TH "Analyzer.cpp" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Analyzer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gml\&.h'\fP
.br
\fC#include 'network\&.h'\fP
.br
\fC#include <random>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef map< string, \fBssnode\fP >
.br
::iterator \fBit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBquery\fP (int q, char *e1, char *e2)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgrph\fP \fBg\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef map<string,\fBssnode\fP>:: iterator \fBit\fP"
.PP
Definition at line 5 of file Analyzer\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (intargc, char **argv)"
.PP
Definition at line 37 of file Analyzer\&.cpp\&.
.SS "void \fBquery\fP (intq, char *e1, char *e2)"Function query calling functions of \fBnetwork\&.h\fP to answer the query 
.PP
Definition at line 10 of file Analyzer\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBgrph\fP \fBg\fP"
.PP
Definition at line 4 of file Analyzer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
