.TH "CompareTime" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareTime \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBids\fP &t1, \fBids\fP &t2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file timeKeeper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CompareTime::operator() (\fBids\fP &t1, \fBids\fP &t2)\fC [inline]\fP"
.PP
Definition at line 42 of file timeKeeper\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
