.TH "CompareDist" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareDist \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBvertex\fP &n1, \fBvertex\fP &n2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
function sizeofclique gives the clique of the given person 
.PP
Definition at line 38 of file network\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CompareDist::operator() (\fBvertex\fP &n1, \fBvertex\fP &n2)\fC [inline]\fP"
.PP
Definition at line 41 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
