.TH "Courses" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Courses \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCourses\fP ()"
.br
.ti -1c
.RI "\fBCourses\fP (string n, string d, float f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBdep_offer\fP"
.br
.ti -1c
.RI "\fBDepartment\fP * \fBdepp_offer\fP"
.br
.ti -1c
.RI "float \fBfreq_peryr\fP"
.br
.ti -1c
.RI "\fBFaculty\fP * \fBprof\fP"
.br
.ti -1c
.RI "vector< \fBStudent\fP * > \fBstudents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure storing \fBInterest\fP with its name and popularity 
.PP
Definition at line 73 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCourses::Courses\fP ()\fC [inline]\fP"
.PP
Definition at line 82 of file I\&.h\&.
.SS "\fBCourses::Courses\fP (stringn, stringd, floatf)\fC [inline]\fP"
.PP
Definition at line 83 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string \fBCourses::dep_offer\fP"
.PP
Definition at line 77 of file I\&.h\&.
.SS "\fBDepartment\fP* \fBCourses::depp_offer\fP"
.PP
Definition at line 78 of file I\&.h\&.
.SS "float \fBCourses::freq_peryr\fP"
.PP
Definition at line 79 of file I\&.h\&.
.SS "string \fBCourses::name\fP"
.PP
Definition at line 76 of file I\&.h\&.
.SS "\fBFaculty\fP* \fBCourses::prof\fP"
.PP
Definition at line 80 of file I\&.h\&.
.SS "vector<\fBStudent\fP*> \fBCourses::students\fP"
.PP
Definition at line 81 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
