.TH "Department" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Department \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDepartment\fP ()"
.br
.ti -1c
.RI "\fBDepartment\fP (string v, int n_f, int n_s, float s_d, float s_n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBnum_faculty\fP"
.br
.ti -1c
.RI "int \fBnum_student_peryr\fP"
.br
.ti -1c
.RI "float \fBsem_deptc\fP"
.br
.ti -1c
.RI "float \fBsem_nondeptc\fP"
.br
.ti -1c
.RI "vector< \fBCourses\fP * > \fBfloatedCourses\fP"
.br
.ti -1c
.RI "vector< \fBFaculty\fP * > \fBdep_faculty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class of university having objects \fBCourses\fP,departments,Hostels,Houselocality,Students,\fBInterest\fP 
.PP
Definition at line 111 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDepartment::Department\fP ()\fC [inline]\fP"
.PP
Definition at line 121 of file I\&.h\&.
.SS "\fBDepartment::Department\fP (stringv, intn_f, intn_s, floats_d, floats_n)\fC [inline]\fP"
.PP
Definition at line 122 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBFaculty\fP*> \fBDepartment::dep_faculty\fP"
.PP
Definition at line 120 of file I\&.h\&.
.SS "vector<\fBCourses\fP*> \fBDepartment::floatedCourses\fP"
.PP
Definition at line 119 of file I\&.h\&.
.SS "string \fBDepartment::name\fP"
.PP
Definition at line 114 of file I\&.h\&.
.SS "int \fBDepartment::num_faculty\fP"
.PP
Definition at line 115 of file I\&.h\&.
.SS "int \fBDepartment::num_student_peryr\fP"
.PP
Definition at line 116 of file I\&.h\&.
.SS "float \fBDepartment::sem_deptc\fP"
.PP
Definition at line 117 of file I\&.h\&.
.SS "float \fBDepartment::sem_nondeptc\fP"
.PP
Definition at line 118 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
