.TH "Faculty" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Faculty \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaculty\fP ()"
.br
.ti -1c
.RI "\fBFaculty\fP (string e, \fBnode\fP *p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBemployecode\fP"
.br
.ti -1c
.RI "\fBnode\fP * \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of \fBStudent\fP 
.PP
Definition at line 182 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFaculty::Faculty\fP ()\fC [inline]\fP"
.PP
Definition at line 187 of file I\&.h\&.
.SS "\fBFaculty::Faculty\fP (stringe, \fBnode\fP *p)\fC [inline]\fP"
.PP
Definition at line 188 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string \fBFaculty::employecode\fP"
.PP
Definition at line 185 of file I\&.h\&.
.SS "\fBnode\fP* \fBFaculty::info\fP"
.PP
Definition at line 186 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
