.TH "globalInterest" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globalInterest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBglobalInterest\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBStudent\fP * > \fBglo_in\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to store students of a particular interest Structure storing different randomseed 
.PP
Definition at line 32 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBglobalInterest::globalInterest\fP ()\fC [inline]\fP"
.PP
Definition at line 34 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBStudent\fP*> \fBglobalInterest::glo_in\fP"
.PP
Definition at line 33 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
