.TH "gml.h" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gml.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'I\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphm\fP"
.br
.ti -1c
.RI "struct \fBssnode\fP"
.br
.ti -1c
.RI "class \fBgrph\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsaveGraph\fP (\fBGraphm\fP *\fBg\fP)"
.br
.ti -1c
.RI "string \fBreturnId\fP (string line)"
.br
.ti -1c
.RI "string \fBreturnEntry\fP (string line)"
.br
.ti -1c
.RI "string \fBreturnid2\fP (string line)"
.br
.ti -1c
.RI "string \fBreturnUniv\fP (string line)"
.br
.ti -1c
.RI "\fBgrph\fP \fBreadGraph\fP (string filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgrph\fP \fBreadGraph\fP (stringfilename)"
.PP
Definition at line 180 of file gml\&.h\&.
.SS "string \fBreturnEntry\fP (stringline)"Function returnid2 
.PP
Definition at line 111 of file gml\&.h\&.
.SS "string \fBreturnId\fP (stringline)"Function returnEntry return the entrynumber of the node 
.PP
Definition at line 100 of file gml\&.h\&.
.SS "string \fBreturnid2\fP (stringline)"Function returnUniv return the university of the node 
.PP
Definition at line 127 of file gml\&.h\&.
.SS "string \fBreturnUniv\fP (stringline)"Struct ssnode to store the data of the node of the graph 
.PP
Definition at line 142 of file gml\&.h\&.
.SS "void \fBsaveGraph\fP (\fBGraphm\fP *g)"Function returnId return Id of the node 
.PP
Definition at line 60 of file gml\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
