.TH "grph" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grph \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gml\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "map< string, \fBssnode\fP > \fBstudent\fP"
.br
.ti -1c
.RI "map< string, string > \fBstudentIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 175 of file gml\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "map<string,\fBssnode\fP> \fBgrph::student\fP"
.PP
Definition at line 177 of file gml\&.h\&.
.SS "map<string,string> \fBgrph::studentIndex\fP"
.PP
Definition at line 178 of file gml\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
