.TH "HOSTEL" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HOSTEL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHOSTEL\fP (string n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "vector< \fBStudent\fP * > \fBstu_hostel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing \fBCourses\fP having specifications 
.PP
Definition at line 60 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHOSTEL::HOSTEL\fP (stringn)\fC [inline]\fP"
.PP
Definition at line 64 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string \fBHOSTEL::name\fP"
.PP
Definition at line 62 of file I\&.h\&.
.SS "vector<\fBStudent\fP*> \fBHOSTEL::stu_hostel\fP"
.PP
Definition at line 63 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
