.TH "I.h" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <omp\&.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <random>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglobalInterest\fP"
.br
.ti -1c
.RI "struct \fBRandomseed\fP"
.br
.ti -1c
.RI "struct \fBHOSTEL\fP"
.br
.ti -1c
.RI "struct \fBCourses\fP"
.br
.ti -1c
.RI "struct \fBInterest\fP"
.br
.ti -1c
.RI "struct \fBDepartment\fP"
.br
.ti -1c
.RI "class \fBUniversity\fP"
.br
.ti -1c
.RI "struct \fBnode\fP"
.br
.ti -1c
.RI "struct \fBFaculty\fP"
.br
.ti -1c
.RI "struct \fBStudent\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcreate\fP (map< int, \fBUniversity\fP * > *Univs, \fBRandomseed\fP *randomseed, map< string, \fBglobalInterest\fP * > *In)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBcreate\fP (map< int, \fBUniversity\fP * > *Univs, \fBRandomseed\fP *randomseed, map< string, \fBglobalInterest\fP * > *In)"
.PP
Definition at line 219 of file I\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
