.TH "ids" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ids \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBids\fP ()"
.br
.ti -1c
.RI "\fBids\fP (long mt, int a, int b, int c)"
.br
.ti -1c
.RI "\fBids\fP ()"
.br
.ti -1c
.RI "\fBids\fP (long mt, int a, int b, int c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmtype\fP"
.br
.ti -1c
.RI "int \fBthread_id\fP"
.br
.ti -1c
.RI "int \fBuniv_id\fP"
.br
.ti -1c
.RI "float \fBtime_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of ids defining identity to different threads 
.PP
Definition at line 32 of file graph\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBids::ids\fP ()\fC [inline]\fP"
.PP
Definition at line 37 of file graph\&.cpp\&.
.SS "\fBids::ids\fP (longmt, inta, intb, intc)\fC [inline]\fP"
.PP
Definition at line 38 of file graph\&.cpp\&.
.SS "\fBids::ids\fP ()\fC [inline]\fP"
.PP
Definition at line 31 of file timeKeeper\&.cpp\&.
.SS "\fBids::ids\fP (longmt, inta, intb, intc)\fC [inline]\fP"
.PP
Definition at line 32 of file timeKeeper\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "long \fBids::mtype\fP"
.PP
Definition at line 33 of file graph\&.cpp\&.
.SS "int \fBids::thread_id\fP"
.PP
Definition at line 34 of file graph\&.cpp\&.
.SS "float \fBids::time_id\fP"
.PP
Definition at line 36 of file graph\&.cpp\&.
.SS "int \fBids::univ_id\fP"
.PP
Definition at line 35 of file graph\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
