.TH "Interest" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterest\fP (string a, float b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "float \fBpopularity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of \fBDepartment\fP storing its name, number of faculty, number of students per year , \fBCourses\fP under the department and faculty under the department 
.PP
Definition at line 94 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBInterest::Interest\fP (stringa, floatb)\fC [inline]\fP"
.PP
Definition at line 101 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string \fBInterest::name\fP"
.PP
Definition at line 97 of file I\&.h\&.
.SS "float \fBInterest::popularity\fP"
.PP
Definition at line 98 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
