.TH "node" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnode\fP ()"
.br
.ti -1c
.RI "\fBnode\fP (string n, \fBDepartment\fP *d, string h, vector< \fBInterest\fP > i, \fBUniversity\fP *u)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "\fBDepartment\fP * \fBdept\fP"
.br
.ti -1c
.RI "string \fBhome\fP"
.br
.ti -1c
.RI "vector< \fBInterest\fP > \fBinterest\fP"
.br
.ti -1c
.RI "vector< string > \fBfriends\fP"
.br
.ti -1c
.RI "vector< \fBCourses\fP * > \fBcourses\fP"
.br
.ti -1c
.RI "\fBUniversity\fP * \fBuniv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of faculty 
.PP
Definition at line 158 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBnode::node\fP ()\fC [inline]\fP"
.PP
Definition at line 168 of file I\&.h\&.
.SS "\fBnode::node\fP (stringn, \fBDepartment\fP *d, stringh, vector< \fBInterest\fP >i, \fBUniversity\fP *u)\fC [inline]\fP"
.PP
Definition at line 169 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBCourses\fP*> \fBnode::courses\fP"
.PP
Definition at line 166 of file I\&.h\&.
.SS "\fBDepartment\fP* \fBnode::dept\fP"
.PP
Definition at line 162 of file I\&.h\&.
.SS "vector<string> \fBnode::friends\fP"
.PP
Definition at line 165 of file I\&.h\&.
.SS "string \fBnode::home\fP"
.PP
Definition at line 163 of file I\&.h\&.
.SS "vector<\fBInterest\fP> \fBnode::interest\fP"
.PP
Definition at line 164 of file I\&.h\&.
.SS "string \fBnode::name\fP"
.PP
Definition at line 161 of file I\&.h\&.
.SS "\fBUniversity\fP* \fBnode::univ\fP"
.PP
Definition at line 167 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
