.TH "Randomseed" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Randomseed \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomseed\fP ()"
.br
.ti -1c
.RI "\fBRandomseed\fP (float a, float b, float c, float d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfaculty_random\fP"
.br
.ti -1c
.RI "float \fBstudent_random\fP"
.br
.ti -1c
.RI "float \fBcourse_random\fP"
.br
.ti -1c
.RI "float \fBfriend_random\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure storing students of a Hostel 
.PP
Definition at line 40 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRandomseed::Randomseed\fP ()\fC [inline]\fP"
.PP
Definition at line 47 of file I\&.h\&.
.SS "\fBRandomseed::Randomseed\fP (floata, floatb, floatc, floatd)\fC [inline]\fP"
.PP
Definition at line 48 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float \fBRandomseed::course_random\fP"
.PP
Definition at line 45 of file I\&.h\&.
.SS "float \fBRandomseed::faculty_random\fP"
.PP
Definition at line 43 of file I\&.h\&.
.SS "float \fBRandomseed::friend_random\fP"
.PP
Definition at line 46 of file I\&.h\&.
.SS "float \fBRandomseed::student_random\fP"
.PP
Definition at line 44 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
