.TH "read.py" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBread\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBread\&.R\fP = open(sys\&.argv[1],'r')"
.br
.ti -1c
.RI "tuple \fBread\&.f1\fP = open('edges\&.txt','w')"
.br
.ti -1c
.RI "tuple \fBread\&.f2\fP = open('vertex\&.txt','w')"
.br
.ti -1c
.RI "tuple \fBread\&.parts\fP = line\&.split(''') f2\&.write(parts[1]+' '+parts[3] + ' ' + parts[5] + '\\n') elif line[1:5] == 'edge': parts = line\&.split(''')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
