.TH "read" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBR\fP = open(sys\&.argv[1],'r')"
.br
.ti -1c
.RI "tuple \fBf1\fP = open('edges\&.txt','w')"
.br
.ti -1c
.RI "tuple \fBf2\fP = open('vertex\&.txt','w')"
.br
.ti -1c
.RI "tuple \fBparts\fP = line\&.split(''') f2\&.write(\fBparts\fP[1]+' '+\fBparts\fP[3] + ' ' + \fBparts\fP[5] + '\\n') elif line[1:5] == 'edge': \fBparts\fP = line\&.split(''')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBread::f1\fP = open('edges\&.txt','w')"
.PP
Definition at line 3 of file read\&.py\&.
.SS "tuple \fBread::f2\fP = open('vertex\&.txt','w')"
.PP
Definition at line 4 of file read\&.py\&.
.SS "tuple \fBread::parts\fP = line\&.split(''') f2\&.write(\fBparts\fP[1]+' '+\fBparts\fP[3] + ' ' + \fBparts\fP[5] + '\\n') elif line[1:5] == 'edge': \fBparts\fP = line\&.split(''')"
.PP
Definition at line 10 of file read\&.py\&.
.SS "tuple \fBread::R\fP = open(sys\&.argv[1],'r')"
.PP
Definition at line 2 of file read\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
