.TH "ssnode" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssnode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gml\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBssnode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBentrynumber\fP"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBuniversity\fP"
.br
.ti -1c
.RI "string \fBparent\fP"
.br
.ti -1c
.RI "vector< string > \fBfriends\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file gml\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBssnode::ssnode\fP ()\fC [inline]\fP"
.PP
Definition at line 168 of file gml\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string \fBssnode::entrynumber\fP"
.PP
Definition at line 163 of file gml\&.h\&.
.SS "vector<string> \fBssnode::friends\fP"
.PP
Definition at line 167 of file gml\&.h\&.
.SS "string \fBssnode::id\fP"
.PP
Definition at line 164 of file gml\&.h\&.
.SS "string \fBssnode::parent\fP"
.PP
Definition at line 166 of file gml\&.h\&.
.SS "string \fBssnode::university\fP"
.PP
Definition at line 165 of file gml\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
