.TH "Student" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Student \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStudent\fP ()"
.br
.ti -1c
.RI "\fBStudent\fP (string e, \fBnode\fP *p, \fBHOSTEL\fP *h, char a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBentrynumber\fP"
.br
.ti -1c
.RI "\fBHOSTEL\fP * \fBhome\fP"
.br
.ti -1c
.RI "char \fBfloorno\fP"
.br
.ti -1c
.RI "int \fBroom\fP"
.br
.ti -1c
.RI "\fBnode\fP * \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function to parse input file and storing data 
.PP
Definition at line 198 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBStudent::Student\fP ()\fC [inline]\fP"
.PP
Definition at line 206 of file I\&.h\&.
.SS "\fBStudent::Student\fP (stringe, \fBnode\fP *p, \fBHOSTEL\fP *h, chara, intb)\fC [inline]\fP"
.PP
Definition at line 207 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string \fBStudent::entrynumber\fP"
.PP
Definition at line 201 of file I\&.h\&.
.SS "char \fBStudent::floorno\fP"
.PP
Definition at line 203 of file I\&.h\&.
.SS "\fBHOSTEL\fP* \fBStudent::home\fP"
.PP
Definition at line 202 of file I\&.h\&.
.SS "\fBnode\fP* \fBStudent::info\fP"
.PP
Definition at line 205 of file I\&.h\&.
.SS "int \fBStudent::room\fP"
.PP
Definition at line 204 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
