.TH "University" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
University \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniversity\fP (string a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBCourses\fP * > \fBCourse\fP"
.br
.ti -1c
.RI "vector< \fBDepartment\fP * > \fBdept\fP"
.br
.ti -1c
.RI "vector< string > \fBHostel\fP"
.br
.ti -1c
.RI "vector< \fBHOSTEL\fP * > \fBhostels_univ\fP"
.br
.ti -1c
.RI "vector< string > \fBHouseLocality\fP"
.br
.ti -1c
.RI "vector< \fBStudent\fP * > \fBstudents\fP"
.br
.ti -1c
.RI "vector< \fBFaculty\fP * > \fBprofs\fP"
.br
.ti -1c
.RI "vector< \fBInterest\fP > \fBInterests_univ\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "float \fBopenness\fP"
.br
.ti -1c
.RI "float \fBfriendliness\fP"
.br
.ti -1c
.RI "float \fBfriendshiprate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of node to define general charachteristic of student and faculty 
.PP
Definition at line 135 of file I\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBUniversity::University\fP (stringa)\fC [inline]\fP"
.PP
Definition at line 150 of file I\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBCourses\fP*> \fBUniversity::Course\fP"
.PP
Definition at line 138 of file I\&.h\&.
.SS "vector<\fBDepartment\fP*> \fBUniversity::dept\fP"
.PP
Definition at line 139 of file I\&.h\&.
.SS "float \fBUniversity::friendliness\fP"
.PP
Definition at line 148 of file I\&.h\&.
.SS "float \fBUniversity::friendshiprate\fP"
.PP
Definition at line 149 of file I\&.h\&.
.SS "vector<string> \fBUniversity::Hostel\fP"
.PP
Definition at line 140 of file I\&.h\&.
.SS "vector<\fBHOSTEL\fP*> \fBUniversity::hostels_univ\fP"
.PP
Definition at line 141 of file I\&.h\&.
.SS "vector<string> \fBUniversity::HouseLocality\fP"
.PP
Definition at line 142 of file I\&.h\&.
.SS "vector<\fBInterest\fP> \fBUniversity::Interests_univ\fP"
.PP
Definition at line 145 of file I\&.h\&.
.SS "string \fBUniversity::name\fP"
.PP
Definition at line 146 of file I\&.h\&.
.SS "float \fBUniversity::openness\fP"
.PP
Definition at line 147 of file I\&.h\&.
.SS "vector<\fBFaculty\fP*> \fBUniversity::profs\fP"
.PP
Definition at line 144 of file I\&.h\&.
.SS "vector<\fBStudent\fP*> \fBUniversity::students\fP"
.PP
Definition at line 143 of file I\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
