.TH "univslen" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
univslen \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmtype\fP"
.br
.ti -1c
.RI "int \fBlenUnivs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file graph\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBunivslen::lenUnivs\fP"
.PP
Definition at line 27 of file graph\&.cpp\&.
.SS "long \fBunivslen::mtype\fP"
.PP
Definition at line 26 of file graph\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
