.TH "vertex" 3 "Tue Nov 19 2013" "Version 1.0" "CSP301 Product2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvertex\fP ()"
.br
.ti -1c
.RI "\fBvertex\fP (string a, \fBssnode\fP b, int c, bool f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBen\fP"
.br
.ti -1c
.RI "\fBssnode\fP \fBvalue\fP"
.br
.ti -1c
.RI "int \fBdistance\fP"
.br
.ti -1c
.RI "bool \fBvisited\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCompareDist\fP function comparator function for priority queue 
.PP
Definition at line 18 of file network\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBvertex::vertex\fP ()\fC [inline]\fP"
.PP
Definition at line 25 of file network\&.h\&.
.SS "\fBvertex::vertex\fP (stringa, \fBssnode\fPb, intc, boolf)\fC [inline]\fP"
.PP
Definition at line 26 of file network\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBvertex::distance\fP"
.PP
Definition at line 23 of file network\&.h\&.
.SS "string \fBvertex::en\fP"
.PP
Definition at line 21 of file network\&.h\&.
.SS "\fBssnode\fP \fBvertex::value\fP"
.PP
Definition at line 22 of file network\&.h\&.
.SS "bool \fBvertex::visited\fP"
.PP
Definition at line 24 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSP301 Product2 from the source code\&.
